name: Bug report
description: Report an unexpected behavior or regression
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include API calls, payloads, and environment details.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or output
      description: Include relevant server logs or errors.
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v0.x.x or commit SHA
